# Identificador único del proyecto (debe coincidir con lo que creaste en SonarCloud)
sonar.projectKey=carrioneilnacr-art_Wayra_Web_Fronted
sonar.organization=carrioneilnacr-art
sonar.token=78b19afcadb129eda0ab19edeb775d84af70698b


# Directorios a analizar
sonar.sources=src
sonar.tests=tests
sonar.test.inclusions=**/*.test.js,**/*.test.jsx

# Excluir archivos que no necesitamos medir
sonar.exclusions=node_modules/**,dist/**,src/assets/**,src/main.jsx,src/App.jsx

# Configuración de Cobertura (Esto lo llenaremos cuando instalemos Vitest)
sonar.javascript.lcov.reportPaths=coverage/lcov.info